"""Add external tools models

Revision ID: 0c75cc61c9ea
Revises: 700e1168cc70
Create Date: 2025-12-15 23:04:41.645766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c75cc61c9ea'
down_revision = '700e1168cc70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('openapi_spec_url', sa.String(length=512), nullable=True),
    sa.Column('openapi_spec', sa.JSON(), nullable=True),
    sa.Column('auth_type', sa.String(length=32), nullable=True),
    sa.Column('auth_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('external_tool_operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('response_schema', sa.JSON(), nullable=True),
    sa.Column('input_mapping', sa.JSON(), nullable=True),
    sa.Column('output_mapping', sa.JSON(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('retry_config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['external_tool.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id', 'operation_id', name='uq_tool_operation')
    )
    op.create_table('external_tool_execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.String(length=140), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('request_url', sa.String(length=1024), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['external_tool_operation.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Note: SQLite doesn't support ALTER COLUMN SET NOT NULL, skipping
    # op.alter_column('proposal', 'proposal_type_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    op.create_foreign_key(None, 'workflow_state', 'form_template', ['form_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_state', type_='foreignkey')
    # Note: SQLite doesn't support ALTER COLUMN, skipping
    # op.alter_column('proposal', 'proposal_type_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    op.drop_table('external_tool_execution')
    op.drop_table('external_tool_operation')
    op.drop_table('external_tool')
    # ### end Alembic commands ###
