"""Add ProposalType and link to Workflow

Revision ID: 0fd963dc2e15
Revises: d87b58fcd8cd
Create Date: 2025-08-01 14:38:57.121433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd963dc2e15'
down_revision = 'd87b58fcd8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        # Add new columns first (nullable to avoid constraint issues)
        batch_op.add_column(sa.Column('proposal_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_state_id', sa.Integer(), nullable=True))
        # Drop old columns (this will automatically drop associated foreign keys in SQLite)
        batch_op.drop_column('proposal_season_id')
        batch_op.drop_column('workflow_state_id')
        # Create new foreign keys after dropping old columns (must have names in batch mode)
        batch_op.create_foreign_key('fk_proposal_current_state', 'workflow_state', ['current_state_id'], ['id'])
        batch_op.create_foreign_key('fk_proposal_proposal_type', 'proposal_type', ['proposal_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_state_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('proposal_season_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(op.f('proposal_proposal_season_id_fkey'), 'proposal_season', ['proposal_season_id'], ['id'])
        batch_op.create_foreign_key(op.f('proposal_workflow_state_id_fkey'), 'workflow_state', ['workflow_state_id'], ['id'])
        batch_op.drop_column('current_state_id')
        batch_op.drop_column('proposal_type_id')
    op.drop_table('proposal_type')
    # ### end Alembic commands ###
