"""Add ProposalType and link to Workflow

Revision ID: 0fd963dc2e15
Revises: d87b58fcd8cd
Create Date: 2025-08-01 14:38:57.121433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd963dc2e15'
down_revision = 'd87b58fcd8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('proposal', sa.Column('proposal_type_id', sa.Integer(), nullable=False))
    op.add_column('proposal', sa.Column('current_state_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('proposal_workflow_state_id_fkey'), 'proposal', type_='foreignkey')
    op.drop_constraint(op.f('proposal_proposal_season_id_fkey'), 'proposal', type_='foreignkey')
    op.create_foreign_key(None, 'proposal', 'workflow_state', ['current_state_id'], ['id'])
    op.create_foreign_key(None, 'proposal', 'proposal_type', ['proposal_type_id'], ['id'])
    op.drop_column('proposal', 'proposal_season_id')
    op.drop_column('proposal', 'workflow_state_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('workflow_state_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('proposal', sa.Column('proposal_season_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'proposal', type_='foreignkey')
    op.drop_constraint(None, 'proposal', type_='foreignkey')
    op.create_foreign_key(op.f('proposal_proposal_season_id_fkey'), 'proposal', 'proposal_season', ['proposal_season_id'], ['id'])
    op.create_foreign_key(op.f('proposal_workflow_state_id_fkey'), 'proposal', 'workflow_state', ['workflow_state_id'], ['id'])
    op.drop_column('proposal', 'current_state_id')
    op.drop_column('proposal', 'proposal_type_id')
    op.drop_table('proposal_type')
    # ### end Alembic commands ###
