"""add_tool_type_and_validation_config

Revision ID: 385388bc973d
Revises: de61f52173ed
Create Date: 2025-12-17 09:19:52.797506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385388bc973d'
down_revision = 'de61f52173ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_tool_operation', sa.Column('tool_type', sa.String(length=32), nullable=True, server_default='other'))
    op.add_column('external_tool_operation', sa.Column('validation_config', sa.JSON(), nullable=True))
    
    # Note: SQLite doesn't support ALTER COLUMN SET NOT NULL, skipping
    # op.alter_column('proposal', 'proposal_type_id', ...)
    
    # Check if foreign key already exists (may have been created in previous migration)
    try:
        op.create_foreign_key(None, 'workflow_state', 'form_template', ['form_template_id'], ['id'])
    except Exception:
        # Foreign key may already exist, skip
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_constraint(None, 'workflow_state', type_='foreignkey')
    except Exception:
        # Constraint may not exist, skip
        pass
    # Note: SQLite doesn't support ALTER COLUMN, skipping
    # op.alter_column('proposal', 'proposal_type_id', ...)
    op.drop_column('external_tool_operation', 'validation_config')
    op.drop_column('external_tool_operation', 'tool_type')
    # ### end Alembic commands ###
