"""update modles

Revision ID: 54a95f593301
Revises: 0fd963dc2e15
Create Date: 2025-11-11 10:03:05.498731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a95f593301'
down_revision = '0fd963dc2e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('workflow_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_transition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('from_state_id', sa.Integer(), nullable=False),
    sa.Column('to_state_id', sa.Integer(), nullable=False),
    sa.Column('allowed_roles', sa.JSON(), nullable=True),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['workflow_action.id'], ),
    sa.ForeignKeyConstraint(['from_state_id'], ['workflow_state.id'], ),
    sa.ForeignKeyConstraint(['to_state_id'], ['workflow_state.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal_instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('form_data', sa.JSON(), nullable=True),
    sa.Column('scheduling_feedback', sa.JSON(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('feedback_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('applicant_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'instrument_id', 'phase', name='uq_proposal_instrument')
    )
    op.create_index('ix_proposal_instrument_queue', 'proposal_instrument', ['instrument_id', 'phase', 'status'], unique=False)
    op.create_table('proposal_phase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proposal_phase_unique', 'proposal_phase', ['proposal_id', 'phase'], unique=True)
    op.create_table('proposal_state_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(length=64), nullable=True),
    sa.Column('to_state', sa.String(length=64), nullable=True),
    sa.Column('transition_name', sa.String(length=140), nullable=True),
    sa.Column('acted_by', sa.String(length=64), nullable=True),
    sa.Column('acted_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrument_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_instrument_id', sa.Integer(), nullable=False),
    sa.Column('scheduler_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_instrument_id'], ['proposal_instrument.id'], ),
    sa.ForeignKeyConstraint(['scheduler_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Add columns that don't need foreign keys (SQLite supports this)
    op.add_column('form_template', sa.Column('phase', sa.String(length=32), nullable=True))
    op.add_column('form_template', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('proposal_season', sa.Column('phase_one_deadline', sa.DateTime(), nullable=True))
    op.add_column('proposal_season', sa.Column('phase_two_deadline', sa.DateTime(), nullable=True))
    
    # Use batch mode for adding columns with foreign keys
    with op.batch_alter_table('form_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_form_template_instrument', 'instrument', ['instrument_id'], ['id'])
    
    with op.batch_alter_table('proposal_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_proposal_type_season', 'proposal_season', ['season_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for dropping columns with foreign keys
    with op.batch_alter_table('proposal_type', schema=None) as batch_op:
        batch_op.drop_constraint('fk_proposal_type_season', type_='foreignkey')
        batch_op.drop_column('season_id')
    
    op.drop_column('proposal_season', 'phase_two_deadline')
    op.drop_column('proposal_season', 'phase_one_deadline')
    
    with op.batch_alter_table('form_template', schema=None) as batch_op:
        batch_op.drop_constraint('fk_form_template_instrument', type_='foreignkey')
        batch_op.drop_column('instrument_id')
    op.drop_column('form_template', 'version')
    op.drop_column('form_template', 'phase')
    op.drop_table('instrument_feedback')
    op.drop_table('proposal_state_history')
    op.drop_index('ix_proposal_phase_unique', table_name='proposal_phase')
    op.drop_table('proposal_phase')
    op.drop_index('ix_proposal_instrument_queue', table_name='proposal_instrument')
    op.drop_table('proposal_instrument')
    op.drop_table('workflow_transition')
    op.drop_table('workflow_action')
    op.drop_table('instrument')
    # ### end Alembic commands ###
