"""Add form_template_id to workflow_state

Revision ID: 700e1168cc70
Revises: 54a95f593301
Create Date: 2025-12-02 14:53:03.896136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700e1168cc70'
down_revision = '54a95f593301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed alter_column for proposal.proposal_type_id as SQLite doesn't support it
    # and it's not necessary for this migration
    op.add_column('workflow_state', sa.Column('form_template_id', sa.Integer(), nullable=True))
    op.add_column('workflow_state', sa.Column('form_required', sa.Boolean(), nullable=True))
    op.add_column('workflow_state', sa.Column('description', sa.Text(), nullable=True))
    # SQLite doesn't support adding foreign key constraints to existing tables
    # The relationship is defined in the model and will work without explicit constraint
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_state', 'description')
    op.drop_column('workflow_state', 'form_required')
    op.drop_column('workflow_state', 'form_template_id')
    # ### end Alembic commands ###
