"""empty message

Revision ID: de61f52173ed
Revises: 0c75cc61c9ea
Create Date: 2025-12-15 23:09:39.087997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de61f52173ed'
down_revision = '0c75cc61c9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: SQLite doesn't support ALTER COLUMN SET NOT NULL, skipping
    # op.alter_column('proposal', 'proposal_type_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    
    # Check if foreign key already exists (may have been created in previous migration)
    # If it doesn't exist, create it
    try:
        op.create_foreign_key(None, 'workflow_state', 'form_template', ['form_template_id'], ['id'])
    except Exception:
        # Foreign key may already exist, skip
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_constraint(None, 'workflow_state', type_='foreignkey')
    except Exception:
        # Constraint may not exist, skip
        pass
    # Note: SQLite doesn't support ALTER COLUMN, skipping
    # op.alter_column('proposal', 'proposal_type_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # ### end Alembic commands ###
